import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

export default [
  {
    // Global ignores
    ignores: [
      'node_modules/',
      'dist/',
      'build/',
      'tmp/',
      'logs/',
      '*.log',
      'pids/',
      '*.pid',
      '*.seed',
      '*.pid.lock',
      '*.swp',
      '*.swo',
      '*.sublime-*',
      '.DS_Store',
      '*copy.*',
      'Thumbs.db',
      '.sfdx/',
      '.sf/',
      'force-app/',
      'venv/',
      'env/',
      'ENV/',
      '__pycache__/',
      '*.pyc',
      '*.pyo',
      '*.pyd',
      '.Python',
      '*.so',
      'notebooks/',
      '*.ipynb',
      '*.config.js',
      '*.config.ts',
      'biome.json',
      'eslint.config.backup.js',
      '.fiveserverrc',
      '*.bak',
      '*.tmp',
      '*.temp',
      '*.old*',
      '.env',
      '.env.*',
      '.git/',
      '.npm-cache/',
      '.npm-tmp/',
      'dev/',
      '*.code-workspace',
      '.cursorignore',
      '.cursorrules',
      'test/',
      '*.bin',
      '*.exe',
      '*.dll',
      '*.so',
      '*.dylib',
      '*.zip',
      '*.tar',
      '*.gz',
      '*.rar',
      '*.db',
      '*.sqlite',
      '*.sqlite3',
      '*.lock',
      'yarn.lock',
      'pnpm-lock.yaml',
      'coverage/',
      '.vscode/',
      '.idea/',
      '.cursor/',
    ],
  },
  {
    files: ['**/*.js', '**/*.ts'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
        project: './tsconfig.json',
      },
      globals: {
        // Node.js globals
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        exports: 'readonly',
        module: 'readonly',
        require: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        globalThis: 'readonly',
        // TypeScript globals
        NodeJS: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      // Base ESLint recommended rules
      ...js.configs.recommended.rules,

      // Code style and formatting rules (equivalent to Biome formatter settings)
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'comma-dangle': ['error', 'never'],
      'indent': ['error', 'tab', { 'SwitchCase': 1 }],
      'max-len': ['error', { code: 300 }],
      'object-curly-spacing': ['error', 'never'],
      'array-bracket-spacing': ['error', 'never'],
      'computed-property-spacing': ['error', 'never'],
      'func-call-spacing': ['error', 'never'],
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'space-in-parens': ['error', 'never'],
      'space-before-blocks': ['error', 'always'],
      'space-before-function-paren': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': ['error', 'always'],
      'brace-style': ['error', '1tbs', { allowSingleLine: false }],
      'comma-spacing': ['error', { before: false, after: true }],
      'comma-style': ['error', 'last'],

      // TypeScript recommended rules
      ...tseslint.configs.recommended.rules,

      // Disable some ESLint rules that conflict with TypeScript
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-redeclare': 'off',
      '@typescript-eslint/no-redeclare': 'error',

      // Additional rules equivalent to Biome rules
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/prefer-as-const': 'error',
      '@typescript-eslint/no-inferrable-types': 'off',

      // Additional JavaScript rules
      'no-console': 'off',
      'no-debugger': 'warn',
      'no-alert': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-labels': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'prefer-const': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-template': 'error',
      'prefer-spread': 'error',
      'prefer-rest-params': 'error',
      'prefer-object-spread': 'error',
      'require-await': 'off',
      'no-return-await': 'off',
      'no-await-in-loop': 'off',
      'no-constant-condition': 'error',
      'no-duplicate-imports': 'error',
      'no-self-compare': 'error',
      'no-template-curly-in-string': 'error',
      'no-unreachable-loop': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-private-class-members': 'warn',
      'require-atomic-updates': 'off',
      'no-loss-of-precision': 'error',
      'no-promise-executor-return': 'off',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-constructor-return': 'error',
      'no-dupe-else-if': 'error',
      'no-import-assign': 'error',
      'no-setter-return': 'error',
      'prefer-exponentiation-operator': 'error',
      'prefer-regex-literals': 'error',
      'default-case-last': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-fallthrough': 'error',
      'no-global-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-misleading-character-class': 'error',
      'no-obj-calls': 'error',
      'no-regex-spaces': 'error',
      'no-sparse-arrays': 'warn',
      'no-unexpected-multiline': 'error',
      'require-yield': 'error',
      'no-new-require': 'error',
      'handle-callback-err': 'error',
      'no-new-object': 'error',
      'no-array-constructor': 'error',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-this': 'off',
      'no-loop-func': 'error',
      'no-multi-str': 'error',
      'no-proto': 'error',
      'no-return-assign': 'error',
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'off',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'off',
      'no-use-before-define': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'off',
      '@typescript-eslint/no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'object-shorthand': 'error',
      'one-var': ['error', 'never'],
      'operator-assignment': 'error',
      'prefer-numeric-literals': 'error',
      'radix': 'error',
      'require-jsdoc': 'off',
      'sort-vars': 'off',
      'strict': ['error', 'never'],
      'vars-on-top': 'off',
      'yoda': 'error',

      // Complexity rules (relaxed to match Biome's high limit)
      'max-depth': ['error', 8],
      'max-nested-callbacks': ['error', 5],
      'max-params': ['error', 8],
      'complexity': ['error', 255],
    },
  },
];